### ISSUE TITLE
Housing Director

### ISSUE THREAD

**Issue by michaelcgorman** [iwu/my.iwu.edu#1]
_From @ckelch on November 12, 2015 18:43_

Here is the link to Housing Director:

https://iwu.datacenter.adirondacksolutions.com/iwu_thdss_test/security/iwu_login.cfm

This is the test instance. We will need to switch to the production environment when we switch portals this summer. We will also need to have some students test this.

_Copied from original issue: iwu/iwu-website#41_

**Comment by michaelcgorman** [comment]
CAS cutover is scheduled for the week of June 6.

**Comment by ckelch** [comment]
This is now working with the production environment on Housing Director!
