### ISSUE TITLE
Service Requests Channel - Doesn't show to Students

### ISSUE THREAD

**Issue by ckelch** [iwu/my.iwu.edu#15]
Looks like the audience for the Service Requests channel is Faculty & Staff. I think this should be changed to all. Students may be asked to use some of these as student workers and some apply to them.

**Comment by michaelcgorman** [comment]
Yes it does. Logged in as ttitan:
![screen shot 2016-06-10 at 10 02 32](https://cloud.githubusercontent.com/assets/313667/15968699/79ca698a-2ef2-11e6-9d9e-35c13eaed706.png)
