### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by aaubryiwu** [iwu/my.iwu.edu#17]
Looks like all the links within "list" channels are trying to go /my.iwu.edu/* instead of www.iwu.edu/*

Do you want me to fix? (Thought you might have speedier method.)

**Comment by michaelcgorman** [comment]
I _could_ make a redirect for all 404s on my to 301 to www, but I'd rather not for performance reasons. Would you mind?

**Comment by aaubryiwu** [comment]
No problem!

**Comment by aaubryiwu** [comment]
I'm assuming there's a delay before the updates show up, but let me know if I missed a step.

**Comment by michaelcgorman** [comment]
The only delay is manual; once changes are made to the code, I have to deploy them. Done.
