### ISSUE TITLE
Announcement Roles

### ISSUE THREAD

**Issue by michaelcgorman** [iwu/my.iwu.edu#5]
_From @ckelch on November 12, 2015 15:16_

Need announcements designated to show in the portal to only show to selected roles. Current roles in MyIWU are as follows:

Faculty-FT
Faculty-PT
Staff-Exempt
Staff-Non-Exempt
Student-Male
Student-Female
Student-Freshmen
Student-Sophomore
Student-Junior
Student-Senior
Student-May-Term
Retirees

Email announcements will go to Regroup. 

_Copied from original issue: iwu/iwu-website#33_

**Comment by michaelcgorman** [comment]
Announcement creation form has been updated. Data source not yet integrated.

On 12 November 2015 at 09:16, ckelch <notifications@github.com> wrote:

> Need announcements designated to show in the portal to only show to
> selected roles. Current roles in MyIWU are as follows:
>
> Faculty-FT
> Faculty-PT
> Staff-Exempt
> Staff-Non-Exempt
> Student-Male
> Student-Female
> Student-Freshmen
> Student-Sophomore
> Student-Junior
> Student-Senior
> Student-May-Term
> Retirees
>
> Email announcements will go to Regroup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iwu/iwu-website/issues/33>.
>



-- 
Michael Gorman '10
Señor Web Developer
Bicycle Committee Chair
Illinois Wesleyan University
309-556-3262
mgorman@iwu.edu
@michaelcgorman <https://twitter.com/michaelcgorman>

**Comment by michaelcgorman** [comment]
Everything but the specific student roles (e.g. Sophomore, May Term, etc.) is done.

**Comment by michaelcgorman** [comment]
Everything but May Term is done. We discussed this at today's Administrative Services meeting and decided it was too big a technological hurdle to get it in there, and not necessary for this year. If it's deemed necessary for next year, @aaubryiwu can file another issue and bring it up again after launch.

**Comment by aaubryiwu** [comment]
Thanks!! I see it as more a necessity for Regroup (with thanks to that team, so we aren't spamming the 1,100 students who aren't expected to be on campus) vs. the portal.
